name = "meattrain"
author = "grace"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcf89244ea4f683d5697124665ffa2617811d1d6877779350ffb11b61f4c7755"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
