name = "meattrain"
author = "grace"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e150147c9bbcdd8ead53787b13bdbc819c145adef5938fd455e730a6e7f20f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
