name = "meattrain"
author = "grace"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fec52af3734cb83ab0ed7b546caac8cdb8cd6e2d7519212903693c4c9cf46399"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
